import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { cn } from '@/lib/utils'
 
const  font = Poppins({ weight:['200','300','400','500','600','700','800','900']  ,subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>  
    <html lang="en"  suppressHydrationWarning >
        <body className={cn(
          font.className,
          "bg-white dark:bg-[#1111]"
        )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          storageKey="discord-theme"
        > 
        {children}
         </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  )
}
